#! /bin/sh

#################################################################
# This is a "simple" script which is intended to be run by rpm
# as a post install function to look at the system where wdm is
# being installed and create Xclients and wdm-config files which
# reflect the window managers available on that system.

#    This software is Copyright (C) 1998 by Gene Czarcinski.
# This software falls under the GNU Public License. Please read
#              the COPYING file for more information
#################################################################

save_ifs="$IFS"
IFS=:
path=$PATH:/usr/local/bin:/usr/bin:/usr/X11R6/bin:

WMLIST=""

rc_word=wmaker
WMAKER_PATH=""
wmakercm="\\# "
    for rc_dir in $path; do
      if test -x $rc_dir/$rc_word; then
        WMAKER_PATH=$rc_dir/$rc_word
	WMLIST=WindowMaker
	wmakercm=""
	break
      fi
    done

rc_word=afterstep
AFTERSTEP_PATH=""
afterstepcm="\\# "
    for rc_dir in $path; do
      if test -x $rc_dir/$rc_word; then
        AFTERSTEP_PATH=$rc_dir/$rc_word
	WMLIST="$WMLIST:AfterStep"
	afterstepcm=""
	break
      fi
    done

rc_word=blackbox
BLACKBOX_PATH=""
blackboxcm="\\# "
    for rc_dir in $path; do
      if test -x $rc_dir/$rc_word; then
        BLACKBOX_PATH=$rc_dir/$rc_word
	WMLIST="$WMLIST:BlackBox"
	blackboxcm=""
	break
      fi
    done

rc_word=icewm
ICEWM_PATH=""
icewmcm="\\# "
    for rc_dir in $path; do
      if test -x $rc_dir/$rc_word; then
        ICEWM_PATH=$rc_dir/$rc_word
	WMLIST="$WMLIST:IceWm"
	icewmcm=""
	break
      fi
    done

rc_word=xsession
XSESSION_PATH=""
xsessioncm="\\# "
    for rc_dir in $path; do
      if test -x $rc_dir/$rc_word; then
        XSESSION_PATH=$rc_dir/$rc_word
	WMLIST="$WMLIST:Xsession"
	xsessioncm=""
	break
      fi
    done

rc_word=startkde
STARTKDE_PATH=""
STARTKDECM="\\# "
    for rc_dir in $path; do
      if test -x $rc_dir/$rc_word; then
        STARTKDE_PATH=$rc_dir/$rc_word
	WMLIST="$WMLIST:KDE"
	STARTKDECM=""
	break
      fi
    done

WINMGRCM="\\# "

# update wdm-config
	rm -f /usr/local/etc/wdm/wdm-config
	sed \
		-e "s:#configdir#:/usr/local/etc/wdm:" \
		-e "s:#bindir#:/usr/local/bin:" \
		-e "s:#SHUTDOWN#:/sbin/shutdown:" \
		-e "s:#logdir#:/var/log:" \
		-e "s:#rundir#:/var/run:" \
		-e "s:#pixmapfile#:Eagle.xpm:" \
		-e "s:#pixmapcomment#:! :" \
		-e "s/#wmlist#/$WMLIST/" \
		/usr/local/etc/wdm/wdm-config.in \
		> /usr/local/etc/wdm/wdm-config
	chmod 644 /usr/local/etc/wdm/wdm-config

# update Xclients
	rm -f /usr/local/etc/wdm/Xclients
	sed -e "s:#XRDB#:/usr/X11R6/bin/xrdb:" \
	    -e "s:\#SHELL\#:/bin/bash -login:" \
	    -e "s'#WMAKER_PATH#'$WMAKER_PATH'" \
	    -e "s'#wmakercm#'$wmakercm'" \
	    -e "s'#AFTERSTEP_PATH#'$AFTERSTEP_PATH'" \
	    -e "s'#afterstepcm#'$afterstepcm'" \
	    -e "s'#BLACKBOX_PATH#'$BLACKBOX_PATH'" \
	    -e "s'#blackboxcm#'$blackboxcm'" \
	    -e "s'#ICEWM_PATH#'$ICEWM_PATH'" \
	    -e "s'#icewmcm#'$icewmcm'" \
	    -e "s'#XSESSION_PATH#'$XSESSION_PATH'" \
	    -e "s'#xsessioncm#'$xsessioncm'" \
	    -e "s'#STARTKDE_PATH#'$STARTKDE_PATH'" \
	    -e "s'#startkdecm#'$STARTKDECM'" \
	    -e "s'#winmgrcm#'$WINMGRCM'" \
		/usr/local/etc/wdm/Xclients.in \
		> /usr/local/etc/wdm/Xclients
	chmod 755 /usr/local/etc/wdm/Xclients

